### ISSUE TITLE
More disk sizes in cloud config

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#28]
The `cloud_config` created by `bbl` contains one disk type:

```
disk_types:
- name: default
  disk_size: 1024
  cloud_properties:
    type: gp2
    encrypted: true
```

Many deployments (e.g. concourse) need control over the disk sizing. I think `bbl` needs to provide more disk types (e.g. 50GB, 100GB, 500GB) and/or support customizing the disk types.

Currently we have to edit the cloud config after `bbl` creates it in order to support our concourse workers; we would prefer that `bbl` was aware of our changes instead of us configuring things out of band.
