### ISSUE TITLE
Possible bug in bbl (bosh-bootloader) created ELB when deploying CloudFoundry (on AWS)

### ISSUE THREAD

**Issue by djvdorp** [pivotal-cf-experimental/bosh-bootloader#42]
Basically, all one needs to do with this amazing `bbl` tool is call the following two commands:

`bbl unsupported-deploy-bosh-on-aws-for-concourse`
`bbl unsupported-create-lbs --type=cf`

This will bootstrap the environment needed in AWS to use BOSH, for example to install CloudFoundry.
With this environment ready, you can try to install the OSS `cf-release` [as described here](https://docs.cloudfoundry.org/deploying/common/deploy.html).

However, this bootstrapped environment contains a minor bug that might cause you to to pull out your hairs. The `router_z1` and `router_z2` instances do get registered correctly to one of the two created ELB's (named `CFRouter` and `CFSSHPro`). One of them, `CFRouter`, seems to be used to route HTTP(S) traffic towards the routers, about the purpose of the other ELB I am unsure at this point.

However, the `CFRouter` will be in a Security Group called `CFRouterSecurityGroup` which does allow traffic on TCP ports 80, 443 and 4443 from everywhere. 

![selection_106](https://cloud.githubusercontent.com/assets/827540/16417323/93949ff0-3d45-11e6-97d3-570d56c031e5.png)

However, the traffic needs to pass from the ELB in `CFRouterSecurityGroup` to the actual `router` instances, which are in a Security Group called `InternalSecurityGroup`. As you can see in the screenshot below, this security group does not allow traffic (from Security Group `CFRouterSecurityGroup`) on TCP ports 80, 443 and 4443, causing all the ELB EC2 instances to have Status `OutOfService` (because the Health Checks fail) and the ELB returning `HTTP 503` on every request.

![selection_107](https://cloud.githubusercontent.com/assets/827540/16417358/ce498ec6-3d45-11e6-8e0e-e1a5f837f01f.png)

To get this setup working, one has to modify the `InternalSecurityGroup` to allow traffic on TCP ports 80, 443 and 4443 to be accepted when it originates from the `CFRouterSecurityGroup` as you can see in the screenshot below.

![selection_108](https://cloud.githubusercontent.com/assets/827540/16417449/35aa59f6-3d46-11e6-9403-8224def22971.png)

Changing this (manually, for now) is the way to go to get a healthy and responsive `CFRouter` ELB and a (presumably) working CloudFoundry installation (on AWS), at least as far as `bosh deploy` has finished successfully. We strongly believe that this should be working out of the box when one runs `bbl unsupported-create-lbs --type=cf`.

**Comment by Amit-PivotalLabs** [comment]
@djvdorp rather than modifying the security group, you're recommended to *add* an additional security group to the resource_pool for your routers.  When you `bbl unsupported-create-lbs --type=cf`, it creates an additional security group that allows the ingress from ELB that's required.  Security group rules are allow-only, and so they are simply additive.

**Comment by Amit-PivotalLabs** [comment]
Hi @djvdorp 

Did you try my suggestion above instead of manually editing the other security group?

I'm also very curious, how far have you been able to get with your deploy of CF + Diego?  What steps have you had to do outside of bbl.  In particular, have you had to do anything related to S3 buckets?

Best,
Amit

**Comment by Amit-PivotalLabs** [comment]
Hi @djvdorp 

Since I got some follow up questions from you via email, I'll close out this issue.

Best,
Amit

**Comment by djvdorp** [comment]
Hi @Amit-PivotalLabs 

Sorry for the late reply -- was caught up in some other things but we are definitely going to wrap this up soon. I reverted my manual edits in the other security group, and am now trying to get it working in the way that you suggested. However, when putting this in my `cf-stub.yml`, it is not giving me the desired output in my compiled manifest (output of running `~/workspace/cf-release/scripts/generate_deployment_manifest aws ~/workspace/cf-prod/cf-stub.yml > ~/workspace/cf-prod-compiled/cf-deployment.yml`) -- am I doing something wrong here?

```
[..]

resource_pools:
  - name: router_z1
    cloud_properties:
      elbs:
        - bbl-aws-2-CFRouter-PBD3OB5PYJMW
      security_groups:
        - bbl-aws-2A1qq-InternalSecurityGroup-16ODWQNMFKPXP # this is the other security group, not sure if this should also be in the list
        - bbl-aws-2A1qq-CFRouterInternalSecurityGroup-BE1ODL97BKSP # this is what you suggested, if I understood you correctly

  - name: router_z2
    cloud_properties:
      elbs:
        - bbl-aws-2-CFRouter-PBD3OB5PYJMW
      security_groups:
        - bbl-aws-2A1qq-InternalSecurityGroup-16ODWQNMFKPXP # this is the other security group, not sure if this should also be in the list
        - bbl-aws-2A1qq-CFRouterInternalSecurityGroup-BE1ODL97BKSP # this is what you suggested, if I understood you correctly

[..]
```

**Comment by Amit-PivotalLabs** [comment]
This is a limitation of the spiff tooling that's currently provided to generate manifests.  We're working on more substantial improvements to that workflow, for now you will need to post-process your manifest to add these things to the routers' resource pool's cloud properties.  More info here: http://bosh.io/docs/aws-cpi.html#resource-pools

**Comment by djvdorp** [comment]
Hi @Amit-PivotalLabs 

Just to confirm -- when manually post-processing your (compiled) manifest (`~/workspace/cf-prod-compiled/cf-deployment.yml`) like this, it works fine, so it seems to be a limitation of the spiff tooling indeed -- and I think that is the only sensible solution for now:

```
- cloud_properties:
    availability_zone: eu-central-1a
    elbs:
    - bbl-aws-2-CFRouter-PBD3OB5PYJMW
    security_groups:
    - bbl-aws-2A1qq-InternalSecurityGroup-16ODWQNMFKPXP
    - bbl-aws-2A1qq-CFRouterInternalSecurityGroup-BE1ODL97BKSP
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c3.large
  env:
    bosh:
      password: REDACTED
  name: router_z1
  network: cf1
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
- cloud_properties:
    availability_zone: eu-central-1b
    elbs:
    - bbl-aws-2-CFRouter-PBD3OB5PYJMW
    security_groups:
    - bbl-aws-2A1qq-InternalSecurityGroup-16ODWQNMFKPXP
    - bbl-aws-2A1qq-CFRouterInternalSecurityGroup-BE1ODL97BKSP
    ephemeral_disk:
      size: 10240
      type: gp2
    instance_type: c3.large
  env:
    bosh:
      password: REDACTED
  name: router_z2
  network: cf2
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: latest
```
